# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# input files
input_project_dir: "{{ hostvars['localhost']['input_project_dir'] }}"
network_spec: "{{ input_project_dir }}/network_spec.yml"
ochami_aarch_64_dir: "/opt/omnia/openchami/aarch64"
pulp_repo_store_path: "{{ ochami_aarch_64_dir }}/pulp.repo"
aarch64_regctl_url: "https://github.com/regclient/regclient/releases/latest/download/regctl-linux-arm64"
pulp_repo_file_path: "/etc/yum.repos.d/pulp.repo"
pulp_webserver_cert_path: "/opt/omnia/pulp/settings/certs/pulp_webserver.crt"
anchors_path: "/etc/pki/ca-trust/source/anchors/pulp_webserver.crt"
regctl_tar_path: "omnia/offline_repo/cluster/aarch64/rhel/10.0/tarball/regctl-linux-arm64/regctl-linux-arm64.tar.gz"
regctl_bin_path: "/usr/local/bin/regctl"

# Error messages
no_inventory_error_msg: "No inventory provided. Please specify an inventory with -i option."
admin_aarch64_empty_error_msg: "The inventory group 'admin_aarch64' does not exist or has no hosts."
admin_aarch64_count_error_msg: "The inventory group 'admin_aarch64' must have exactly one host."
network_spec_syntax_fail_msg: "Failed to load network_spec.yml due to syntax error"
pulp_repo_missing_error_msg: "pulp.repo file not found. Please run local_repo.yml playbook to create a repo file."
not_aarch64_error_msg: "This is not an aarch64 machine. Only ARM nodes can be used to build the image."
repo_not_found_error_msg: "The aarch64_baseos repo section is not available in pulp.repo"
nfs_not_configured_msg: >
  To build aarch64 images on an ARM node, the NFS server must be configured on the OIM.
  Please run oim_cleanup.yml and reinstall the omnia_core container with the NFS option.
aarch64_image_fail_msg: >
  Unable to pull the Ochami aarch64 image builder image.
  Make sure you have added the default package for aarch64 in the software_config.json file and ran local_repo.yml.
  If not, add that package and rerun local_repo.yml.
