# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# ***********************************************************************
# DO NOT REMOVE OR COMMENT OUT ANY LINES IN THIS FILE.
# SIMPLY APPEND THE REQUIRED VALUES AGAINST THE PARAMETER OF YOUR CHOICE.
# ***********************************************************************

#*************************************************************************************************************************
# Groups
#*************************************************************************************************************************
# functional_groups_config.yml file takes input parameters for the composable roles and groups.
# This file contains functional groups and Groups used by the omnia for cluster formation.
# Groups: - Groups will contain the list of groups defined by the user. User must define atleast one group.
#   grpN:                 - <Mandatory> "grpN" -  User defined name of the group. Range for N is 0-99
#     location_id:        - <Mandatory> SU-<n>.RACK-<n> Scalable unit and rack number range is 0-99. This input is case-sensitive. Please use uppercase letters only.
#     parent:             - <Conditional Mandatory> list of service tag of associated active service node(s).
#                         - This field will be mandatory for group of nodes which is associated with 'slurm_node' functional_groups.
#                         - This should be in some xname format.
#                         - eg:- parent: "x1000c1s7b1n1"
groups:
  grp0:
    location_id: SU-1.RACK-1
    parent: ""

  grp1:
    location_id: SU-1.RACK-1
    parent: ""

# ************************************************************************************************************************
#  functional_groups
# ************************************************************************************************************************
# Note: Nested functional_groups are not supported.
# The functional_groups are case sensitive
#   - name:               - <Mandatory> Name of the functional_group, can be any of the following Omnia defined functional_groups.
#     cluster_name:       - <Conditional Mandatory> Name of the cluster to which the group belongs. This input is case-sensitive.
#                            This will remain empty for groups which are not associated with any kubernetes functional_groups.
#     group:              - <Mandatory> list of groups defined by the user
#                         - This should be unique for each functional_group
#

# This table lists the functional_groups and the layers they belong to in the cluster.

# +----------------------------------+-------------------+     +------------------------+--------------+
# | Functional Group Name            | Layer             |     | Functional Group Name  | Layer        |
# +----------------------------------+-------------------+     +------------------------+--------------+
# |  service_kube_node_x86_64        | management        |     | slurm_node_x86_64      | compute      |
# |  login_node_x86_64               | management        |     | slurm_node_aarch64     | compute      |
# |  login_node_aarch64              | management        |     |                        |              |
# |  login_compiler_node_x86_64      | management        |     |                        |              |
# |  login_compiler_node_aarch64     | management        |     |                        |              |
# |  slurm_control_node_x86_64       | management        |     |                        |              |
# +----------------------------------+-------------------+     +------------------------+--------------+
#
#
# Recommended software should be present in software_config.json file for each functional_group of x86_64:
#
# +----------------------------------+--------------------------------------------------------------------------------------+
# | Functional Group Name            | Recommended Software                                                                 |
# +----------------------------------+--------------------------------------------------------------------------------------+
# | service_kube_node_x86_64         | service_k8s.json, nfs.json, openldap.json, ofed.json                                 |
# | slurm_control_node_x86_64        | slurm_custom.json, nfs.json, openldap.json, ofed.json                                |
# | slurm_node_x86_64                | slurm_custom.json, nfs.json, openldap.json, ofed.json, cuda.json                     |
# | login_node_x86_64                | slurm_custom.json, nfs.json, openldap.json, ofed.json                                |
# | login_compiler_node_x86_64       | slurm_custom.json, nfs.json, openldap.json, ofed.json, ucx.json, openmpi.json        |
# +----------------------------------+--------------------------------------------------------------------------------------+
#
# Slurm Head functional_groups: (x86_64)
# -----------------------------------------------------------------------------------------------------
#
# This functional_group is used to configure the nodes for Slurm head. It belongs to the management layer.
#
# The nodes included in this functional_group will have the necessary tools and
# configurations to run Slurm head.
#
# The nodes in this functional_group can be used to run Slurm head.
# This functional_group belongs to the compute layer.
functional_groups:
  - name: "slurm_control_node_x86_64"
    cluster_name: "slurm_cluster"
    group:
      - grp0

#
# Slurm Worker functional_groups: (x86_64 / aarch64)
# ------------------------------------------------------------------------------------------------
#
# This functional_group is used to configure the nodes for Slurm worker. It belongs to the compute layer.
#
# The nodes included in this functional_group will have the necessary tools and
# configurations to run Slurm worker.
#
# The nodes in this functional_group can be used to run Slurm worker.
#
  - name: "slurm_node_x86_64"
    cluster_name: "slurm_cluster"
    group:
      - grp1

  # - name: "slurm_node_aarch64"
  #   cluster_name: "slurm_cluster"
  #   group:
  #     - grp2

#
# Service k8s Worker functional_groups: (x86_64)
# ---------------------------------------------------------------------------------------------------
#
# This functional_group is used to configure the nodes for Kubernetes worker on service cluster.
#
# This functional_group should not have same group as of K8s Worker node.
#
# The nodes included in this functional_group will have the necessary tools and
# configurations to configure Kubernetes worker on service cluster.
#
# The nodes in this functional_group can be used to run Kubernetes worker on service cluster.
#
  # - name: "service_kube_node_x86_64"
  #   cluster_name: "service_cluster"
  #   group:
  #     - grp3

#
# Login Node functional_groups: (x86_64 / aarch64)
# ----------------------------------------------------------------------------------------------
#
# This functional_group is used to configure the nodes for user logins. It belongs to the management layer.
#
# The nodes included in this functional_group will have the necessary tools and configurations
# to support user login activities.
#
# The user is not allowed to change the name of this functional_group.
#
  # - name: "login_node_x86_64"
  #   cluster_name: "slurm_cluster"
  #   group:
  #     - grp4

  # - name: "login_node_aarch64"
  #   cluster_name: "slurm_cluster"
  #   group:
  #     - grp5

#
# Login_Compiler Node functional_groups: (x86_64 / aarch64)
# ------------------------------------------------------------------------------------------------
#
# This functional_group is used to configure the nodes for compilation. It belongs to the management layer.
#
# The nodes included in this functional_group will have the necessary tools and
# configurations to perform compilation.
#
# The nodes in this functional_group can be used to compile the code.
#
  # - name: "login_compiler_node_x86_64"
  #   cluster_name: "slurm_cluster"
  #   group:
  #     - grp6

  # - name: "login_compiler_node_aarch64"
  #   cluster_name: "slurm_cluster"
  #   group:
  #     - grp7
