# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# ***********************************************************************
# DO NOT REMOVE OR COMMENT OUT ANY LINES IN THIS FILE.
# SIMPLY APPEND THE REQUIRED VALUES AGAINST THE PARAMETER OF YOUR CHOICE.
# ***********************************************************************

# -----------------------------NFS------------------------------------------------

# This variable is used for mounting NFS share on slurm_control_node, slurm_node, login_node
# This takes a list of dicts with possible keys server_ip, server_share_path, client_share_path, client_mount_options
# In both the cases, the USER must manually update 'server_ip' and 'server_share_path' below with the correct values.
# If mount_option values are empty, NFS client will be mounted with these values "nosuid,rw,sync,hard,intr"
# Its mandatory to provide atleast one entry in nfs_client_params
# Example for single mount file system:
# nfs_client_params:
# nfs_name : str ,Name of the NFS storage resource. The default is "nfs_storage_default".
#     The user can assign any custom string to specify a different NFS storage resource.
# - { server_ip: 10.5.0.101, server_share_path: "/mnt/share", client_share_path: "/home", client_mount_options: "nosuid,rw,sync,hard"}
# Example for supporting multiple mount points:
# nfs_client_params:
# - { server_ip: 198.168.0.1,server_share_path: "/mnt/share1", client_share_path: "/home", client_mount_options: "nosuid,rw,sync,hard"}
# - { server_ip: 198.168.0.2, server_share_path: "/mnt/share2", client_share_path: "/mnt/mount2", client_mount_options: "nosuid,rw,sync,hard"}
# Example for multiple mount file system:
# nfs_client_params:
# - { server_ip: 198.168.0.1, server_share_path: "/mnt/share1", client_share_path: "/mnt/mount1", client_mount_options: "nosuid,rw,sync,hard"}
# - { server_ip: 198.168.0.2, server_share_path: "/mnt/share2", client_share_path: "/mnt/mount2", client_mount_options: "nosuid,rw,sync,hard"}
nfs_client_params:
  - server_ip: "" # Provide the IP of the NFS server
    server_share_path: "/mnt/share/omnia" # Provide server share path of the NFS Server
    client_share_path: /share_omnia
    client_mount_options: "nosuid,rw,sync,hard,intr"
    nfs_name: nfs_slurm
  
  - server_ip: "" # Provide the IP of the NFS server
    server_share_path: "/mnt/share/omnia_k8s" # Provide server share path of the NFS Server
    client_share_path: /share_omnia_k8s
    client_mount_options: "nosuid,rw,sync,hard,intr"
    nfs_name: nfs_k8s
