# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Configure NTP
  block:
    - name: Setup NTP
      ansible.builtin.command: "{{ xcat_path }}/makentp"
      changed_when: true
      async: "{{ async_time }}"
      poll: "{{ poll_time }}"

    - name: Configure postscripts for NTP
      ansible.builtin.command: "{{ xcat_path }}/chdef all -p postscripts=setupntp"
      changed_when: true

  rescue:
    - name: Warning - Failed to configure NTP
      ansible.builtin.pause:
        prompt: "{{ setup_ntp_warning_msg }}"
        seconds: "{{ warning_time }}"
