# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Set variables
  ansible.builtin.set_fact:
    rdma_plugin_commit: false

# ------------------NETWORK ATTACHMENT DEFINITIONS------------------------

- name: Create macvlan configs with NetworkAttachmentDefinitions
  ansible.builtin.command: "kubectl apply -f {{ roce_nad_tmp_folder }}"
  changed_when: true

# ------------------------RDMA PLUGIN-----------------------------
- name: Get rdma-plugin git folder
  ansible.builtin.get_url:
    url: "{{ rdma_plugin_git_url }}"
    dest: "{{ rdma_plugin_dest_folder }}"
    mode: "{{ git_permissions }}"

- name: Unarchive rdma_plugin git folder
  ansible.builtin.unarchive:
    src: "{{ rdma_plugin_dest_folder }}"
    dest: "{{ tmp_folder }}"
    mode: "{{ git_permissions }}"
    remote_src: true

- name: Apply rdma-plugin.patch
  ansible.posix.patch:
    src: "{{ rdma_patch_file_dest }}"
    remote_src: true
    basedir: "{{ rdma_plugin_folder }}"
    strip: 1
  when: true

- name: Install RDMA plugin
  ansible.builtin.command: "kubectl apply -k {{ rdma_plugin_folder }}/deployment/k8s/overlay/"
  changed_when: true

- name: Update imagePullPolicy
  ansible.builtin.command: >
    kubectl patch daemonset rdma-shared-dp-ds -n kube-system --type='json'
    -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/imagePullPolicy", "value":"IfNotPresent"}]'
  changed_when: false
