# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Define variables
  ansible.builtin.set_fact:
    image_versions: []

- name: Fetch and store image versions
  ansible.builtin.set_fact:
    image_versions: "{{ image_versions + [item.package + ':' + item.tag] }}"
  loop: "{{ hostvars['localhost']['roce_plugin_packages_json']['roce_plugin']['cluster'] }}"
  when: item.type == 'image'

- name: Pull Images to nodes
  ansible.builtin.command: "nerdctl pull {{ item }}"
  changed_when: false
  loop: "{{ image_versions }}"
  failed_when: false
  environment:
    http_proxy: "{{ hostvars['localhost']['http_proxy'] }}"
    https_proxy: "{{ hostvars['localhost']['https_proxy'] }}"
    no_proxy: "{{ hostvars['localhost']['oim_hostname'] }},{{ hostvars['localhost']['admin_nic_ip'] }}"
