# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Take a backup of the grub file
  ansible.builtin.copy:
    src: "{{ grub_path }}"
    dest: "{{ grub_path }}.bak"
    mode: "{{ file_permission }}"
    remote_src: true

- name: Update kernel parameters
  ansible.builtin.command: "sudo grubby --update-kernel=ALL --args='{{ cmdline_value }}'"
  register: output
  changed_when: output.rc != 0
  when: cmdline_value != ""
