# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Validate service cluster kube_control_plane group exists
  ansible.builtin.assert:
    that: 
      - "'kube_control_plane' in groups"  
    fail_msg: "{{ service_kube_control_plane_group_fail_msg }}"

- name: Validate BMC IP is defined for kube_control_plane nodes
  ansible.builtin.assert:
    that:
      - "hostvars[item]['bmc_ip'] is defined"
      - "hostvars[item]['bmc_ip'] != ''"
    fail_msg: "{{ service_kube_node_details_fail_msg }}"
  loop: "{{ groups['kube_control_plane'] }}"

- name: Validate kube_control_plane BMC IP is a valid IPv4 address
  ansible.builtin.assert:
    that:
      - "hostvars[item]['bmc_ip'] is match('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b')"
    fail_msg: "{{ service_kube_control_plane_invalid_ip_fail_msg }} {{ item }}:{{ hostvars[item]['bmc_ip'] }}"
  loop: "{{ groups['kube_control_plane'] }}"

- name: Validate BMC group data file exists
  ansible.builtin.stat:
    path: "{{ bmc_group_data_filename }}"
  register: bmc_group_data_stat

- name: Fail if BMC group data file does not exist
  ansible.builtin.fail:
    msg: "{{ bmc_group_data_file_not_found_msg }}"
  when: not bmc_group_data_stat.stat.exists

- name: Read BMC group data
  ansible.builtin.set_fact:
    bmc_group_data: "{{ lookup('file', bmc_group_data_filename).splitlines() }}"

- name: Validate BMC group data file
  validate_bmc_group_data:
    bmc_group_data_headers: "{{ bmc_group_data_headers }}"
    bmc_group_data: "{{ bmc_group_data }}"
    bmc_group_data_file: "{{ bmc_group_data_filename }}"
  register: bmc_ip_data

- name: Set validated BMC ips
  ansible.builtin.set_fact:
    bmc_ips: "{{ bmc_ip_data.bmc_ips }}"
