# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Run pulp status command on omnia_core container
  ansible.builtin.command: /usr/local/bin/pulp status
  delegate_to: localhost
  changed_when: false
  register: pulp_status_output

- name: Set pulp content origin value
  ansible.builtin.set_fact:
    pulp_content_origin: "{{ (pulp_status_output.stdout | from_json).content_settings.content_origin }}"

- name: Set fact for pulp protocol
  ansible.builtin.set_fact:
    pulp_protocol: "{{ pulp_content_origin | urlsplit('scheme') | lower }}"
    pulp_server_ip: "{{ pulp_content_origin | urlsplit('hostname') }}"
    pulp_server_port: "{{ pulp_content_origin | urlsplit('port') }}"

- name: Create local_repo_access.yml file
  ansible.builtin.template:
    src: "{{ local_repo_access_src_path }}"
    dest: "{{ local_repo_access_dest_path }}"
    mode: "{{ file_permission }}"

- name: Include var for local_repo_access.yml file
  ansible.builtin.include_vars: "{{ local_repo_access_dest_path }}"

- name: Remove existing {{ syncfiles_share_path }} directory # noqa: name[template]
  ansible.builtin.file:
    path: "{{ syncfiles_share_path }}"
    state: absent

- name: Remove existing {{ synclists_dir }} directory # noqa: name[template]
  ansible.builtin.file:
    path: "{{ synclists_dir }}"
    state: absent

- name: Create directory syncfiles under /opt/omnia/provision
  ansible.builtin.file:
    path: "{{ syncfiles_share_path }}"
    state: directory
    mode: "{{ dir_permission }}"

- name: Create repos directory under syncfiles directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "{{ dir_permission }}"
  with_items:
    - "{{ repos_share_path_x86_64 }}"
    - "{{ repos_share_path_aarch64 }}"

- name: Create conf directory under syncfiles directory
  ansible.builtin.file:
    path: "{{ syncfiles_share_path }}/conf"
    state: directory
    mode: "{{ dir_permission }}"

- name: Copy Pulp crt to syncfiles
  when: pulp_protocol == 'https'
  block:
    - name: Create certs directory under syncfiles directory
      ansible.builtin.file:
        path: "{{ syncfiles_share_path }}/certs"
        state: directory
        mode: "{{ dir_permission }}"
      when: pulp_protocol == 'https'

    - name: Copy pulp cert to syncfiles certs directory
      ansible.builtin.copy:
        src: "{{ pulp_crt_path }}"
        dest: "{{ syncfiles_share_path }}/certs"
        mode: "{{ file_permission }}"
        remote_src: true

- name: Render pip.conf template
  ansible.builtin.template:
    src: "{{ pip_conf_src }}"
    dest: "{{ pip_conf_dest }}"
    mode: "{{ file_permission }}"
