# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: discover_mapping_nodes.yml
openchami_nodes_template: "{{ role_path }}/templates/nodes/nodes.yaml.j2"
openchami_share_path: /opt/omnia/openchami
openchami_clone_path: "{{ openchami_share_path }}/deployment-recipes"
openchami_smd_log_path: "{{ openchami_log_dir }}/smd.log"
openchami_nodes_vars_path: "{{ openchami_clone_path }}/dell/podman-quadlets/inventory/group_vars/ochami/nodes.yaml"
openchami_config_vars_path: "{{ openchami_share_path }}/configs_vars.yaml"

# Usage: configure_bss.yml
rhel_base_compute_image_name: rhel-compute
bss_template: bss/bss.yaml.j2
openchami_work_dir: "{{ openchami_share_path }}/workdir"
bss_dir: "{{ openchami_work_dir }}/boot"
bss_params_cloud_init: 'ds=nocloud;s=http://{{ cluster_boot_ip }}:8081/cloud-init/'
bss_params_opts: 'ip=dhcp rd.live.image rd.live.ram rd.neednet=1 rd.driver.blacklist=ccp,edac_core,power_meter,ahci,megaraid_sas modprobe.blacklist=ccp,edac_core,power_meter,ahci,megaraid_sas libata.force=1:disable,2:disable,3:disable,4:disable rd.luks=0 rd.md=0 rd.dm=0 console=tty0 console=ttyS0,115200 selinux=0 apparmor=0 ip6=off cloud-init=enabled'

# Usage: configure_cloud_init.yml
ssh_key_path: /root/.ssh/oim_rsa.pub
ci_defaults_template: cloud_init/ci-defaults.yaml.j2
ci_defaults_dest: '{{ openchami_work_dir }}/cloud-init/ci-defaults.yaml'
ci_group_compute_template: cloud_init/ci-group-compute.yaml.j2
ci_group_compute_dest: '{{ openchami_work_dir }}/cloud-init/ci-group-compute.yaml'
