# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: main.yml
python_version: "{{ ansible_python_interpreter }}"
provision_shared_library_path: "/opt/omnia/shared_libraries/provision"
script_name: "{{ provision_shared_library_path }}/common/inventory_tagging.py"
db_path: "{{ provision_shared_library_path }}/db_operations"
omnia_inventory_dir_path: "/opt/omnia/omnia_inventory"
inventory_files_creation_msg: "Inventory files created at '/opt/omnia/omnia_inventory/'"
commentedconfigparser_python_package: "commented-configparser"
inventory_files:
  - compute_cpu_intel
  - compute_cpu_amd
  - compute_cpu_nvidia
  - compute_gpu_nvidia
  - compute_gpu_amd
  - compute_gpu_intel
  - compute_hostname_ip
  - cluster_layout

vendors:
  cpu:
    intel: compute_cpu_intel
    amd: compute_cpu_amd
    nvidia: compute_cpu_nvidia
  gpu:
    nvidia: compute_gpu_nvidia
    amd: compute_gpu_amd
    intel: compute_gpu_intel
