# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Task for set osimage to node object for mapping
  block:
    - name: Set osimage to node object for mapping
      nodeset:
        discovery_mechanism: "{{ mapping_node_group }}"
        install_osimage_x86_64: "{{ provision_os_image_x86_64 }}"
        install_osimage_aarch64: "{{ provision_os_image_aarch64 }}"
        service_osimage: "{{ service_os_image }}"
      changed_when: false
      register: set_osimage_mapping

    - name: Status for nodeset command
      ansible.builtin.debug:
        msg: "{{ set_osimage_mapping.nodes_updated }} {{ mapping_xcat_install_success_msg }}"
      when:
        - set_osimage_mapping.nodes_updated is defined
        - set_osimage_mapping.nodes_updated | length > 0
  rescue:
    - name: Verify set node object is successful for mapping
      ansible.builtin.debug:
        msg: "{{ mapping_set_osimage_warning_msg }} {{ set_osimage_mapping.stderr }}"
      when: set_osimage_mapping.stderr is defined
