#  Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Initialize Variables
  ansible.builtin.set_fact:
    k8s_existing_nodes: []
    k8s_new_nodes_list: []
    k8s_new_nodes: ''
    k8s_installation_status: false
    kube_vip_present: false

- name: Check whether k8s is installed
  ansible.builtin.command: kubectl get nodes -o='Name'
  register: kubectl_status
  changed_when: kubectl_status.rc == 0
  failed_when: false

- name: Set the k8s installation status
  ansible.builtin.set_fact:
    k8s_installation_status: true
  when: kubectl_status.rc == 0

- name: Get K8s pods
  ansible.builtin.command: kubectl get pods --all-namespaces
  changed_when: false
  register: k8s_pods
  failed_when: false

- name: Set kube_vip_present flag
  ansible.builtin.set_fact:
    kube_vip_present: true
  when: "'kube-vip' in k8s_pods.stdout"

- name: Gather the new nodes from inventory
  when: k8s_installation_status
  block:
    - name: Fetch the nodes where k8s is installed
      ansible.builtin.set_fact:
        k8s_existing_nodes: "{{ k8s_existing_nodes + [item.split('/')[1]] }}"
      with_items: "{{ kubectl_status.stdout_lines }}"

    - name: Fetch the new nodes
      ansible.builtin.set_fact:
        k8s_new_nodes_list: >-
          {{ (groups['kube_node'] | difference(k8s_existing_nodes))
            if 'kube_node' in groups else [] }}

    - name: Create new node string
      ansible.builtin.set_fact:
        k8s_new_nodes: >-
          {{ (k8s_new_nodes_list | join(',')) if k8s_new_nodes_list | length > 0 else '' }}
