#  Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Prepare k8s nodes
  when: hostvars['127.0.0.1']['k8s_support']
  block:
    - name: Generate k8s var file
      ansible.builtin.include_tasks: generate_k8s_vars.yml

    - name: Update the inventory with kube vip interface
      ansible.builtin.include_tasks: update_inv.yml
      when:
        - hostvars['127.0.0.1']['enable_k8s_ha']

    - name: Copy docker login file
      ansible.builtin.include_tasks: docker_login.yml

    - name: Prepare hosts file
      ansible.builtin.include_tasks: prepare_hosts_file.yml

    - name: Install prereq
      ansible.builtin.include_tasks: prereq.yml

    - name: Configure firewalld
      ansible.builtin.include_tasks: configure_firewall.yml
      when: not firewall_disable

    - name: Disable firewalld
      ansible.builtin.include_tasks: disable_firewalld.yml
      when: firewall_disable

    - name: Validate share_path is NFS
      ansible.builtin.include_tasks: validate_share_path.yml

    - name: Fetch the nodes where k8s is running
      ansible.builtin.include_tasks: fetch_k8s_nodes.yml
      when: '"kube_control_plane" in group_names'

- name: Perform nerdctl login
  when: not hostvars['127.0.0.1']['k8s_support']
  ansible.builtin.debug:
    msg: "k8s is not supported, skipping prepare nodes"
