# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Fresh cluster - Include common tasks
  ansible.builtin.include_tasks: common.yml

- name: Install configs on all
  ansible.builtin.include_tasks: _config_files.yml
  when: '"slurm_control_node" in group_names'

- name: Include controller installation tasks (This will take a few minutes for nfs_share slurm)
  ansible.builtin.include_tasks: controller.yml
  when: '"slurm_control_node" in group_names'

- name: Include slurm DBD installation tasks
  ansible.builtin.include_tasks: dbd.yml
  when: '"slurm_dbd" in group_names'

- name: Include compute installation tasks
  ansible.builtin.include_tasks: compute.yml
  when: '"slurm_node" in group_names'

- name: Include login node installation tasks
  ansible.builtin.include_tasks: login.yml
  when: '"login_node" in group_names'
