# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Configure default postbootscripts
  ansible.builtin.command: "{{ xcat_path }}/chdef all postbootscripts=\"otherpkgs\""
  changed_when: true

- name: Configure hostname postbootscripts
  ansible.builtin.command: "{{ xcat_path }}/chdef all -p postbootscripts=\"omnia_hostname\""
  changed_when: true

- name: Configure postbootscripts for confignetwork
  ansible.builtin.command: "{{ xcat_path }}/chdef all -p postbootscripts=\"confignetwork\""
  changed_when: true

- name: Copy omnia_ssh_check script to postbootscripts
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ omnia_ssh_check_postbootscripts_path }}"

- name: Configure SSH services check postbootscripts
  ansible.builtin.command: "{{ xcat_path }}/chdef all -p postbootscripts=\"omnia_ssh_check\""
  changed_when: true

- name: Configure syncfiles postbootscripts
  ansible.builtin.command: "{{ xcat_path }}/chdef all -p postbootscripts=\"syncfiles\""
  changed_when: true
