# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: csi_powerscale_config_certificate.yml
empty_certificate_path: "{{ csi_powerscale_path }}/empty_isilon-certs.yaml"
fail_msg_empty_certificate: "Failed. Unable to create empty certificate."
empty_certificate_template_path: "{{ role_path }}/files/empty_certificate_template.yml"

# Usage: csi_powerscale_config_secret.yml, csi_powerscale_prereq.yml
input_project_dir: "{{ hostvars['localhost']['input_project_dir'] }}"
csi_powerscale_secret_path: "{{ csi_powerscale_path }}/csi_powerscale_secret.yaml"

# Usage: csi_powerscale_install.yml, csi_powerscale_prereq.yml
csi_powerscale_path: "/opt/omnia/csi-driver-powerscale"
ansible_python_interpreter: "/usr/bin/{{ hostvars['localhost']['python_package'] }}"

# Usage: csi_powerscale_install.yml, csi_powerscale_prereq.yml
csi_powerscale_git: "csi-powerscale.tar.gz"

# Usage: csi_powerscale_install.yml
fail_msg_csi_powerscale_driver: "Error. Deployment of csi driver was not successful. Please review the deployment. Run playbook with -vvv for more details"
pass_msg_csi_powerscale_driver: "CSI Powerscale driver installation completed successfully."
wait_time: 10
warning_wait_time: 30
max_attempts: 5
isilon_ns: "isilon"
async_time: 180
poll_time: 10

# Usage: csi_powerscale_prereq.yml
permission_644: "0644"
owner_value: "root"
group_value: "root"
powerscale_ns: "isilon"
powerscale_pod_indcator: "isilon-"
csi_powerscale_values_path: "{{ csi_powerscale_path }}/values.yaml"
fail_msg_download: "Failed to get required dependencies. Make sure to verify entries in csi_driver_powerscale.json and run local_repo.yml first."
helm_charts_git: "helm-charts.tar.gz"
external_snapshotter_git: "external-snapshotter.tar.gz"
k8s_not_deployed: "Failed, Kubernetes is not deployed on the cluster. Run omnia.yml with k8s entry in software_config.json to install kubernetes first."
helm_not_deployed: "Failed, Helm is not deployed on the cluster."
csi_powerscale_secret_vaultname: ".csi_powerscale_secret_vault"
vault_key_permission: "0644"
warning_msg_already_deployed: "Powerscale will not be deployed. Existing powerscale deployment is already present on the cluster.
 Please remove the existing powerscale deployment first using steps mentioned in omnia document and rerun playbook to install powerscale."

# Usage: template ps_storage_class.j2
ps_isipath: "{{ hostvars['localhost']['csi_powerscale_values_file']['isiPath'] }}"
ps_access_zone: "{{ hostvars['localhost']['csi_powerscale_values_file']['isiAccessZone'] }}"
