# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Verify image, kernel and initramfs in S3
  ansible.builtin.shell: s3cmd ls -Hr s3://boot-images | grep {{ rhel_base_compute_image_name }} | grep {{ hostvars['localhost']['cluster_os_version'] }} | awk '{print $4}' | sed 's|s3://||'
  changed_when: false
  register: verify_s3_image

- name: Verify s3 image output
  ansible.builtin.debug:
    msg: "{{ verify_s3_image.stdout_lines }}"

- name: Initialize kernel and initrd
  ansible.builtin.set_fact:
    kernel: ""
    initrd: ""

- name: Set kernel and initrd variables
  ansible.builtin.set_fact:
    kernel: "{{ verify_s3_image.stdout_lines | select('search', 'vmlinuz') | list | first }}"
    initrd: "{{ verify_s3_image.stdout_lines | select('search', 'initramfs') | list | first }}"
  when: verify_s3_image.stdout_lines | length > 1

- name: Fail if kernel or initrd length less than 1
  ansible.builtin.fail:
    msg: "Failed to set kernel or initrd. Please verify the compute image created"
  when: kernel | length < 1 or initrd | length < 1

- name: Load bss template - {{ functional_group_name }}
  ansible.builtin.template:
    src: "{{ bss_template }}"
    dest: "{{ bss_dir }}/bss-{{ functional_group_name }}.yaml"
    mode: "{{ hostvars['localhost']['file_permissions_644'] }}"

- name: Set boot configuration - {{ functional_group_name }}
  ansible.builtin.command: ochami bss boot params set -f yaml -d @{{ openchami_work_dir }}/boot/bss-{{ functional_group_name }}.yaml
  changed_when: true
