# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Delete all ochami component endpoints
  ansible.builtin.command: /usr/bin/ochami smd compep delete --no-confirm --all
  changed_when: true
  failed_when: false

- name: Delete all ochami redfish endpoints
  ansible.builtin.command: /usr/bin/ochami smd rfe delete --no-confirm --all
  changed_when: true
  failed_when: false

- name: Delete all ochami iface
  ansible.builtin.command: /usr/bin/ochami smd iface delete --no-confirm --all
  changed_when: true
  failed_when: false
