# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Create oim group and provision group
  ansible.builtin.import_playbook: ../utils/create_container_group.yml
  vars:
    oim_group: true
  tags: always

- name: Openchmi build image
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - image_creation
