# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitastions under the License.
---

- name: Set ubuntu_kernel_flavor for Ubuntu 20.04
  ansible.builtin.set_fact:
    ubuntu_kernel_flavor: "hwe"
  when:
    - provision_os | lower == os_supported_ubuntu
    - provision_os_version | string == ubuntu20_version

- name: Configure hwe kernel
  when: ubuntu_kernel_flavor | default("generic", true) == 'hwe'
  block:
    - name: Check hwe kernel applied
      ansible.builtin.shell: >
        set -o pipefail && \
        cat {{ debian_plugin_path }} | grep '{{ hwe_search_key }}'
      changed_when: false
      failed_when: false
      register: hwe_kernel_check

    - name: Apply hwe kernel patch
      when: hwe_search_key not in hwe_kernel_check.stdout
      block:
        - name: Copy hwe kernel patch
          ansible.builtin.copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            mode: "{{ item.mode }}"
          with_items: "{{ hwe_patch_path }}"

        - name: Patch hwe kernel file
          ansible.builtin.shell: patch debian.pm < debian_hwe.patch # noqa: command-instead-of-module
          changed_when: true
          args:
            chdir: "{{ xcat_plugin_path }}"

        - name: Delete hwe kernel script patch
          ansible.builtin.file:
            path: "{{ item.dest }}"
            state: absent
          with_items: "{{ hwe_patch_path }}"

- name: Configure generic kernel
  when:
    - provision_os | lower == os_supported_ubuntu
    - provision_os_version | string in ubuntu22_version
    - ubuntu_kernel_flavor | default("generic", true) == 'generic'
  block:
    - name: Check generic kernel applied
      ansible.builtin.shell: >
        set -o pipefail && \
        cat {{ debian_plugin_path }} | grep '{{ hwe_search_key }}'
      changed_when: false
      failed_when: false
      register: generic_kernel_check

    - name: Apply generic kernel patch
      when: hwe_search_key in generic_kernel_check.stdout
      block:
        - name: Copy generic kernel patch
          ansible.builtin.copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            mode: "{{ item.mode }}"
          with_items: "{{ generic_patch_path }}"

        - name: Patch generic kernel file
          ansible.builtin.shell: patch debian.pm < debian_generic.patch # noqa: command-instead-of-module
          changed_when: true
          args:
            chdir: "{{ xcat_plugin_path }}"

        - name: Delete generic kernel script patch
          ansible.builtin.file:
            path: "{{ item.dest }}"
            state: absent
          with_items: "{{ generic_patch_path }}"
