# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: include_inputs.yml
discovery_inputs:
  - path: "{{ hostvars['localhost']['input_project_dir'] }}/provision_config.yml"
  - path: "{{ hostvars['localhost']['input_project_dir'] }}/network_spec.yml"
  - path: "{{ hostvars['localhost']['input_project_dir'] }}/functional_groups_config.yml"
  - path: "/opt/omnia/.data/oim_metadata.yml"

input_syntax_fail_msg: "Failed. Syntax errors present in {{ item.path }}. Fix errors and re-run playbook again."

# Usage: include_software_config.yml
software_config_file: "{{ hostvars['localhost']['input_project_dir'] }}/software_config.json"
software_config_syntax_fail_msg: "Failed. Syntax errors present in software_config.json. Fix errors and re-run playbook again."

# Usage: validate_mapping_mechanism.yml
invalid_mapping_fail_msg: |
  "Failed. pxe_mapping_file_path should be a valid path in provision_config.yml.
  Please provide valid path and re-run the playbook.

# Usage: validate_mapping_file.yml
mapping_file_key: "ADMIN_MAC"
hostname_chars_fail_msg: |
  Failed. Hostname should not contain _ or . or space or node- as it might result in issues with provisioning/authentication
  tools like FreeIPA. Make sure the mapping file contains only the hostname, and not the domain_name. Found in:
temp_mapping_file_path: "/opt/omnia/pxe_mapping_file.csv"
capital_hostname_fail_msg: |
  "Failed. Invalid hostname {{ item }}. Hostname should be in lower case and should not start with numbers.
  Refer documentation for more details."
temp_pxe_file_path: "/opt/omnia/openchami/temp_pxe_file.csv"
file_mode: "0644"
functional_groups_file_path: "{{ hostvars['localhost']['input_project_dir'] }}/functional_groups_config.yml"

# Usage: updates_hosts.yml
hosts_file_path: /opt/omnia/hosts
