# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

container_removal_failure_msg: " container could not be removed. Please check container logs."
omnia_nfs_share: "{{ hostvars['localhost']['oim_shared_path'] }}/omnia"
telemetry_cleanup_directory:
  - "{{ omnia_nfs_share }}/telemetry"
  - "{{ omnia_nfs_share }}/.secrets"
  - "{{ omnia_nfs_share }}/log/telemetry"
  - "{{ omnia_nfs_share }}/k8s_pvc_data"
  - "{{ omnia_nfs_share }}/service_cluster"
max_retries: 5
omnia_target: "/etc/systemd/system/omnia.target"

# Usage: cleanup_pulp.yml
pulp_container_name: "pulp"
pulp_cleanup_directory:
  - "{{ omnia_nfs_share }}/pulp/pulp_ha/cli.toml"
  - "{{ omnia_nfs_share }}/log/pulp"
  - "{{ omnia_nfs_share }}/pulp/settings"
  - "{{ omnia_nfs_share }}/pulp/nginx"
  - "{{ project_input_path }}/.local_repo_credentials_key"
  - "{{ omnia_nfs_share }}/offline_repo"
  - "{{ omnia_nfs_share }}/log/local_repo"
  - "{{ omnia_nfs_share }}/k8s_dynamic_json"
track_file_path: "{{ omnia_nfs_share }}/pulp/pulp_crt_track.txt"

# Usage: cleanup_kubespray.yml
kubespray_cleanup_directory:
  - "{{ omnia_nfs_share }}/kubespray"
  - "{{ omnia_nfs_share }}/log/kubespray"

# Usage: cleanup_openchami.yml
openchami_packages:
  - ochami
  - openchami
  - s3cmd

openchami_containers:
  - minio-server
  - registry
  - step-ca
  - postgres
  - hydra
  - opaal-idp
  - smd
  - bss
  - opaal
  - cloud-init-server
  - haproxy
  - coresmd

openchami_volumes:
  - haproxy-certs
  - acme-certs
  - postgres-data
  - step-ca-db
  - step-root-ca
  - step-ca-home

openchami_secrets:
  - hydra_postgres_password
  - hydra_dsn
  - hydra_system_secret
  - smd_postgres_password
  - postgres_password
  - postgres_multiple_databases
  - bss_postgres_password

tcp_ports:
  - 9000
  - 9001
  - 5000
  - 5432
  - 27778
  - 27779
  - 8081
  - 8443

udp_ports:
  - 69
  - 67
  - 68

podman_interfaces:
  - podman0
  - podman1
  - podman2
  - podman3
  - podman4

systemd_files:
  - /etc/containers/systemd/registry.container
  - /etc/containers/systemd/minio.container

regctl_files:
  - ~/.regctl/config.json
  - /usr/local/bin/regctl

config_dirs:
  - /etc/openchami
  - /etc/ochami
  - "{{ omnia_nfs_share }}/openchami"
  - "{{ omnia_nfs_share }}/log/openchami"

omnia_target_file:
  - /etc/systemd/system/omnia.target