# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: include_security_config.yml
security_config_file: "{{ hostvars['localhost']['input_project_dir'] }}/security_config.yml"
login_node_security_config_file: "{{ hostvars['localhost']['input_project_dir'] }}/login_node_security_config.yml"
hosts_file_dest: "/etc/hosts"
hosts_file_mode: "0644"
security_config_syntax_fail_msg: "Failed. Syntax errors present in security_config.yml. Fix errors and re-run playbook again."

# Usage: validate_input_params.yml
min_length: 8
max_length: 30
domain_name_length: '63'
domain_name_success_msg: "domain name successfully validated"
domain_name_fail_msg: "Failed. Incorrect format provided for domain name in security_config.yml"
realm_name_success_msg: "realm_name successfully validated"
realm_name_fail_msg: "Failed. Incorrect realm_name formate in security_config.yml"
input_config_failure_msg: "Failed. Since, authentication_system is freeipa, provide domain_name and realm_name in input/security_config.yml."
secure_login_node_success_msg: "secure_login_node present in input/software_config.json."
secure_login_node_fail_msg: "Failed. enable_secure_login_node should be either true or false"
secure_login_node_warning_msg: "[WARNING] secure_login_node present in input/software_config.json and
login_node group not provided with login_node IP address in inventory. Skipping tasks for secure login node configuration"
ubuntu_freeipa_support_fail_msg: "Failed. freeipa is not supported on ubuntu. Remove freeipa from software_config.json and rerun the playbook"
proxy_env_fail_msg: "Failed. The values for http_proxy and https_proxy in the
proxy variable of the site_config.yml should be set as environment variables http_proxy and https_proxy in the Omnia Infrastructure Manager.
The no_proxy environment variable should include the Omnia Infrastructure Manager hostname and the admin network IP address."

# Usage: fetch_security_inputs.yml
max_failures_success_msg: "max_failures successfully validated"
max_failures_fail_msg: "Failed. Incorrect max_failures value in login_node_security_config.yml"
failure_reset_interval_success_msg: "failure_reset_interval successfully validated"
failure_reset_interval_fail_msg: "Failed. Incorrect failure_reset_interval value in login_node_security_config.yml"
lockout_duration_success_msg: "lockout_duration successfully validated"
lockout_duration_fail_msg: "Failed. Incorrect lockout_duration value in login_node_security_config.yml"
session_timeout_success_msg: "session_timeout successfully validated"
session_timeout_fail_msg: "Failed. Incorrect session_timeout value in login_node_security_config.yml"
root_user_absence: "Warning: root user not provide in allow list of user. 'root' will not have the privilege to access the login_node."
warning_wait_time_warning: 15
max_failures_default_value: 3
failure_reset_interval_min_value: 30
failure_reset_interval_max_value: 60
lockout_duration_min_value: 5
lockout_duration_max_value: 10
session_timeout_min_value: 90
session_timeout_max_value: 180
alert_email_success_msg: "alert_email_address successfully validated"
alert_email_fail_msg: "Failed. Incorrect alert_email_address value in login_node_security_config.yml"
alert_email_warning_msg: "[WARNING] alert_email_address is empty. Authentication failure alerts won't be configured."
email_max_length: 320
email_search_key: "@"
user_success_msg: "user successfully validated"
user_fail_msg: "Failed. Incorrect user format in login_node_security_config.yml"
allow_deny_success_msg: "Access successfully validated"
allow_deny_fail_msg: "Failed. Incorrect Access format in login_node_security_config.yml"
restrict_program_support_success_msg: "restrict_program_support successfully validated"
restrict_program_support_failure_msg: "Failed. Accepted values are true or false."
restrict_softwares_success_msg: "restrict_softwares successfully validated"
restrict_softwares_failure_msg: "Warning. Values should be comma separated. The supported services are telnet,lpd,bluetooth,rlogin,rexec."
smtp_server_fail_msg: "Failed. smtp_server details are mandatory when alert_email_address provide in login_node_security_config.yml.
Provide SMTP server host, port and sender_address with single SMTP server details for sending alert email."

# Usage: fetch_ldap_client_inputs.yml
ldap_client_config_failure_msg: "LDAP Client Input parameters cannot be empty when ldap_reqired is set to true"
ldap_server_failure_msg: "LDAP server is not reachable. Please check the reachability from cluster"
ping_msg: "100% packet loss"
ldap_connection_type_success_msg: "LDAP Connection type successfully validated"
ldap_connection_type_fail_msg: "Failed. LDAP Connection type must be: SSL, TLS, ssl or tls"
ldap_ca_cert_path_failure_msg: "Failed. The mentioned certificate does not exist"

# Usage: set_login_node_status.yml
multiple_login_node_fail_msg: "Failed. Currently only one login node supported in inventory"
warning_wait_time: 30
login_node_warning_msg: "[WARNING] login_node group with ip for login_node not present in the inventory. Proceeding execution with auth_server and other nodes"

# Usasge: fetch_ldap_server_inputs.yml
ldap_cert_path_fail_msg: "Failed, LDAP certificate path doesn't exist."
ldap_cert_path_success_msg: "LDAP certificate path validated"
fail_msg_ltb_dir: "Failed, LTB directory doesn't exist."
local_repo_access_config_file: "/opt/omnia/provision/local_repo_access.yml"

# Usage: generate_ldap_password_hashes.yml
hashing_python_file: "{{ role_path }}/files/generate_hash.py"
python_version: "{{ ansible_python_interpreter }}"

# Usage: ldap_prereq.yml
openldap_packages_file: "{{ hostvars['localhost']['input_project_dir'] }}/config/{{ software_config.cluster_os_type }}/{{ software_config.cluster_os_version }}/openldap.json"  # noqa: yaml[line-length]
ldap_dir: "/opt/omnia/ldap"
ltb_git_repo_path: "ansible-role-ldaptoolbox-openldap"
ldap_git_dir: "/opt/omnia/ldap/ansible-role-ldaptoolbox-openldap"
openldap_software_failure_msg: "Failed, OpenLDAP software stack is not present in software_config.json file.
Update openldap software stack in software_config.json and execute local_repo.yml."
ldap_repo_failure_msg: "Failed. The OpenLDAP repository is missing. Please run the local_repo.yml playbook to download the required OpenLDAP packages.
Once the playbook has been successfully executed, you can rerun the original playbook."
file_permission: '0644'

# Usage: fetch_software_config.yml
software_config_json_file: "{{ hostvars['localhost']['input_project_dir'] }}/software_config.json"
freeipa_and_openldap_false_fail_msg: "Both freeipa and openldap are not present in software_config.json.
Please give one of them in software_config.json and execute local_repo.yml again."
freeipa_and_openldap_true_fail_msg: "Both freeipa and openldap are present in software_config.json.
Please give only one of them in software_config.json"
compute_os_ubuntu: "ubuntu"
ipa_support_wait_time: 30
ipa_support_warning: "Skipping the configuration of the secure login node
because the software_config.json file does not contain either 'freeipa' or 'openldap' as the authentication system.
To enable the configuration of the secure login node, please provide either 'freeipa' or 'openldap' in the software_config.json file."
