#  Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Include variable file omnia_config.yml
  ansible.builtin.include_vars: "{{ omnia_config_vars }}"
  register: include_omnia_config
  no_log: true

- name: Prepare service_k8s_cluster NFS mapping
  ansible.builtin.set_fact:
    service_k8s_nfs_map: >-
      {{
        service_k8s_cluster
        | selectattr('deployment', 'truthy')
        | map(attribute='nfs_storage_name')
        | select('truthy')
        | list
        | first
      }}
  when: service_k8s_support | bool

- name: Prepare compute_k8s_cluster NFS mapping
  ansible.builtin.set_fact:
    compute_k8s_nfs_map: >-
      {{
        compute_k8s_cluster
        | selectattr('deployment', 'truthy')
        | map(attribute='nfs_storage_name')
        | select('truthy')
        | list
        | first
        | default('')
      }}
  when: compute_k8s_support | bool

- name: Prepare slurm_cluster NFS mapping
  ansible.builtin.set_fact:
    slurm_nfs_map: >-
      {{
        slurm_cluster
        | selectattr('deployment', 'truthy')
        | map(attribute='nfs_storage_name')
        | select('truthy')
        | list
        | first
        | default('')
      }}
  when: slurm_support | bool

- name: Print service_k8s_nfs_map
  ansible.builtin.debug:
    msg: "{{ service_k8s_nfs_map }}"
