---
- name: Read Processor NodeParams
  ansible.builtin.uri:
    url: "https://{{ bmc_ip_map[item] }}/redfish/v1/Systems/System.Embedded.1/Processors?$expand=*($levels=1)"
    user: "{{ bmc_username }}"
    password: "{{ bmc_password }}"
    method: GET
    force_basic_auth: true
    validate_certs: false
    return_content: true
    body_format: json
    timeout: 60
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
      OData-Version: "4.0"
    status_code:
      - 200
  register: proc_info

- name: Calculate proc facts
  ansible.builtin.set_fact:
    proc_params: "{{ {} | combine({'Sockets': (proc_info.json.Members | length)})
     | combine({'CoresPerSocket': (proc_info.json.Members[0].TotalEnabledCores)})
     | combine({'ThreadsPerCore': (proc_info.json.Members[0].TotalThreads // proc_info.json.Members[0].TotalCores)}) }}"

- name: Add to Nodeparam dict
  ansible.builtin.set_fact:
    node_params: "{{ node_params | default({}) | combine({item: proc_params}) }}"
