#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
- name: Read Processor NodeParams
  ansible.builtin.uri:
    url: "https://{{ bmc_ip_map[item] }}/redfish/v1/Systems/System.Embedded.1/Processors?$expand=*($levels=1)"
    user: "{{ bmc_username }}"
    password: "{{ bmc_password }}"
    method: GET
    force_basic_auth: true
    validate_certs: false
    return_content: true
    body_format: json
    timeout: 60
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
      OData-Version: "4.0"
    status_code:
      - 200
  register: proc_info
  failed_when: false

- name: Get CPU Processors list # to filter out GPUs
  ansible.builtin.set_fact:
    cpus: "{{ proc_info.json.Members | default({}) | selectattr('ProcessorType', 'equalto', 'CPU') | list }}"

- name: Calculate proc facts
  ansible.builtin.set_fact:
    proc_params: "{{ {} | combine({'Sockets': (1 if (cpus | length == 0) else (cpus | length))})
     | combine({'CoresPerSocket': (cpus[0].TotalEnabledCores | default(1))})
     | combine({'ThreadsPerCore': ((cpus[0].TotalThreads | default(1)) // (cpus[0].TotalCores | default(1)))}) }}"

- name: Add to Nodeparam dict
  ansible.builtin.set_fact:
    node_params: "{{ node_params | default({}) | combine({item: proc_params}) }}"
