# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Include and initialize variables

- name: Set server host
  ansible.builtin.set_fact:
    node_host: >-
      {{
        hostvars[inventory_hostname]['inventory_hostname']
        if inventory_hostname != 'localhost'
        else 'oim'
      }}

- name: Initialize variables
  ansible.builtin.set_fact:
    telemetry_idrac: []
    service_type: 3
    auth_type: 1
    idrac_ip_count: 0
    telemetry_idrac_count: 0
    failed_idrac_count: 0
    failed_idrac: []

- name: Include telemetry common vars
  ansible.builtin.include_vars: "{{ playbook_dir }}/roles/telemetry_validation/vars/main.yml"
  no_log: true

- name: Include Service k8s telemetry common vars
  ansible.builtin.include_vars: "{{ playbook_dir }}/roles/service_k8s_telemetry/vars/main.yml"
  no_log: true

- name: Fetch iDRAC BMC IPs for each pod
  fetch_idrac_ips:
    service_cluster_metadata: "{{ service_cluster_metadata }}"
    parent_to_bmc_ip_details: "{{ hostvars['localhost']['bmc_ips'] }}"
  register: idrac_podname_idracips

- name: Show iDRAC IPs for each pod
  ansible.builtin.debug:
    msg: >-
      "iDRAC IPs for pod '{{ item.key }}': {{ item.value | join(', ') }}"
  loop: "{{ idrac_podname_idracips.idrac_podname_ips | dict2items }}"
  when: idrac_podname_idracips.idrac_podname_ips is defined and idrac_podname_idracips.idrac_podname_ips

- name: Read the existing BMC IP's from mysqlDB of the idrac telemetry pods
  read_idracips_from_mysqldb:
    telemetry_namespace: "{{ telemetry_namespace }}"
    idrac_podnames: "{{ idrac_podname_idracips.idrac_podname_ips.keys() | list }}"
    mysqldb_k8s_name: "{{ mysqldb_k8s_name }}"
    mysqldb_name: "{{ mysqldb_name }}"
    mysqldb_root_password: "{{ hostvars['localhost']['mysqldb_root_password'] }}"
    db_retries: "{{ db_retries }}"
    db_delay: "{{ db_delay }}"
  register: existing_mysqldb_idracips

- name: Set existing BMC IPs from mysqlDB
  ansible.builtin.set_fact:
    existing_mysqldb_idracips: "{{ existing_mysqldb_idracips.mysqldb_idrac_ips }}"
    existing_pod_to_db_idrac_ips: "{{ existing_mysqldb_idracips.pod_to_db_idrac_ips }}"

- name: Set fact for bmc_ips
  ansible.builtin.set_fact:
    bmc_ips: "{{ hostvars['localhost']['bmc_ips'].values() | flatten }}"

- name: Generate filtered iDRAC IP list
  ansible.builtin.set_fact:
    filtered_bmc_ip_list: "{{ bmc_ips | difference(existing_mysqldb_idracips) }}"

- name: Show filtered BMC IPs
  ansible.builtin.debug:
    msg: "Filtered BMC IPs: {{ filtered_bmc_ip_list }}"

- name: Convert filtered_bmc_ip_list to a dictionary with bmc_ip
  ansible.builtin.set_fact:
    filtered_bmc_ip_dict_list: "{{ filtered_bmc_ip_list | map('community.general.dict_kv', 'bmc_ip') | list }}"

- name: Validate BMC reachability
  update_bmc_group_entry:
    nodes: "{{ filtered_bmc_ip_dict_list }}"
    bmc_username: "{{ hostvars['localhost']['bmc_username'] }}"
    bmc_password: "{{ hostvars['localhost']['bmc_password'] }}"
    verify_bmc: true
  register: bmc_result

- name: Show verified BMC entries
  when: bmc_result.verified_bmc | length > 0
  ansible.builtin.debug:
    msg: "BMC entries valid for IPs: {{ bmc_result.verified_bmc | join(', ') }}"

- name: Show Redfish Disabled Warning
  when: bmc_result.redfish_disabled | length > 0
  ansible.builtin.debug:
    msg: "{{ redfish_disabled_msg | replace('\n', ' ') }}"

- name: Show Invalid BMC Credentials
  when: bmc_result.invalid_creds | length > 0
  ansible.builtin.debug:
    msg: "{{ invalid_creds_msg | replace('\n', ' ') }}"

- name: Show Unreachable BMC IPs
  when: bmc_result.unreachable_bmc | length > 0
  ansible.builtin.debug:
    msg: >-
      {{
        unreachable_oim_bmc_msg | replace('\n', ' ')
        if node_host == 'oim'
        else unreachable_service_node_bmc_msg | replace('\n', ' ')
      }}

- name: Warning for user to fix BMC issues
  when: >
    (bmc_result.redfish_disabled | length > 0) or
    (bmc_result.invalid_creds | length > 0) or
    (bmc_result.unreachable_bmc | length > 0)
  ansible.builtin.pause:
    seconds: "{{ waiting_time_30 }}"
    prompt: "{{ invalid_bmc_warning_msg }}"

- name: Set fact for BMC IPs validation bmc bmc result
  ansible.builtin.set_fact:
    idrac_redfish_disabled: "{{ bmc_result.redfish_disabled }}"
    idrac_invalid_creds: "{{ bmc_result.invalid_creds }}"
    idrac_unreachable: "{{ bmc_result.unreachable_bmc }}"
    invalid_idrac_count: >-
      {{ (bmc_result.invalid_creds + bmc_result.unreachable_bmc + bmc_result.redfish_disabled) | length }}
    invalid_idrac_list: >-
      {{ bmc_result.invalid_creds + bmc_result.unreachable_bmc + bmc_result.redfish_disabled }}

- name: Filter iDRACs based on telemetry pre-requisites
  block:
    - name: Filter iDRACs matching telemetry pre-requisites (This task may take more time based on number of iDRACs)
      idrac_telemetry_filter:
        bmc_ip_list: "{{ bmc_result.verified_bmc }}"
        bmc_username: "{{ hostvars['localhost']['bmc_username'] }}"
        bmc_password: "{{ hostvars['localhost']['bmc_password'] }}"
        min_firmware_version_reqd: "{{ min_firmware_version_reqd }}"
      register: filter_idrac_output
      when:
        - bmc_result.verified_bmc is defined
        - bmc_result.verified_bmc | length > 0
  rescue:
    - name: Failed to filter iDRACs
      ansible.builtin.fail:
        msg: "{{ filter_idrac_fail_msg }} Error: {{ filter_idrac_output.msg }}"

- name: Update the telemetry variables with filtered iDRACs
  ansible.builtin.set_fact:
    telemetry_idrac: "{{ filter_idrac_output.telemetry_idrac }}"
    telemetry_idrac_count: "{{ filter_idrac_output.telemetry_idrac_count }}"
    failed_idrac_count: "{{ filter_idrac_output.failed_idrac_count }}"
    failed_idrac: "{{ filter_idrac_output.failed_idrac }}"
  when:
    - filter_idrac_output.telemetry_idrac is defined
    - filter_idrac_output.telemetry_idrac_count is defined

- name: Enable telemetry collection on iDRAC
  when: telemetry_idrac is defined and (telemetry_idrac | length > 0)
  block:
    - name: Enable telemetry collection on iDRACs
      ansible.builtin.command: >-
        python3 ./ConfigurationScripts/EnableOrDisableAllTelemetryReports.py -ip "{{ item }}"
        -u "{{ hostvars['localhost']['bmc_username'] }}" -p "{{ hostvars['localhost']['bmc_password'] }}" -s Enabled
      args:
        chdir: "{{ idrac_telemetry_scripting_git_clone_path }}"
      with_items: "{{ telemetry_idrac }}"
      changed_when: false
      no_log: true
  rescue:
    - name: Failed to enable the iDRAC telemetry
      ansible.builtin.debug:
        msg: "{{ idrac_telemetry_enable_fail_msg | replace('\n', ' ') }}"

- name: Add iDRAC details in mysqldb
  when: telemetry_idrac is defined and (telemetry_idrac | length > 0)
  insert_idracips_mysqldb:
    telemetry_namespace: "{{ telemetry_namespace }}"
    idrac_podnames_ips: "{{ idrac_podname_idracips.idrac_podname_ips }}"
    mysqldb_k8s_name: "{{ mysqldb_k8s_name }}"
    mysqldb_name: "{{ mysqldb_name }}"
    mysqldb_root_password: "{{ hostvars['localhost']['mysqldb_root_password'] }}"
    bmc_username: "{{ hostvars['localhost']['bmc_username'] }}"
    bmc_password: "{{ hostvars['localhost']['bmc_password'] }}"
    telemetry_idrac: "{{ telemetry_idrac }}"
    service_type: "{{ service_type }}"
    auth_type: "{{ auth_type }}"
    db_retries: "{{ db_retries }}"
    db_delay: "{{ db_delay }}"
  register: add_idrac_to_db

- name: Show iDRACs added to mysqldb
  ansible.builtin.debug:
    msg: >-
      iDRACs added to mysqldb: {{ add_idrac_to_db.results | default('No results returned') }}

- name: Show iDRACs failed to add to mysqldb
  ansible.builtin.debug:
    msg: >-
      "iDRACs failed to add to mysqldb: {{ add_idrac_to_db.failed_ips | default('No failed IPs') }}"
