# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Check for existing NFS Client Provisioner
  kubernetes.core.k8s_info:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: nfs-client
  register: nfs_client_sc
  ignore_errors: true

- name: Check if CSI Provisioner StorageClass (ps01) exists
  kubernetes.core.k8s_info:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: ps01
  register: csi_storage_class
  ignore_errors: true

- name: Remove default annotation from NFS Client Provisioner if it is default and ps01 exists
  kubernetes.core.k8s:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: nfs-client
    merge_type: strategic-merge
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
  when: (nfs_client_sc.resources | length > 0) and
          (csi_storage_class.resources | length > 0) and
          ('storageclass.kubernetes.io/is-default-class' in nfs_client_sc.resources[0].metadata.annotations) and
          (nfs_client_sc.resources[0].metadata.annotations['storageclass.kubernetes.io/is-default-class'] == "true")

- name: Set CSI Provisioner as default StorageClass if it exists
  kubernetes.core.k8s:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: ps01
    merge_type: strategic-merge
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
  when: csi_storage_class.resources | length > 0
