# Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Remove existing isilon-creds secret if present
  kubernetes.core.k8s:
    api_version: v1
    kind: Secret
    name: isilon-creds
    namespace: "{{ powerscale_ns }}"
    state: absent
  register: delete_secret_result
  failed_when: false
  changed_when: delete_secret_result.changed

- name: Create isilon-creds secret in isilon namespace
  ansible.builtin.command: kubectl create secret generic isilon-creds -n {{ powerscale_ns }} --from-file=config="{{ csi_powerscale_secret_path }}"
  failed_when: false
  register: apply_secret
  changed_when: apply_secret.changed

- name: Get existing isilon-creds secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ powerscale_ns }}"
    name: isilon-creds
  register: existing_secret

- name: Decode the config from secret
  set_fact:
    decoded_config: "{{ existing_secret.resources[0].data.config | b64decode | from_yaml }}"

- name: Update username and password in decoded config
  set_fact:
    updated_config: >-
      {{
        decoded_config | combine({
          'isilonClusters': [ decoded_config.isilonClusters[0] | combine({
            'username': correct_username,
            'password': correct_password
          }) ]
        })
      }}

- name: Encode updated config to base64
  set_fact:
    encoded_config: "{{ updated_config | to_nice_yaml(indent=2) | b64encode }}"

- name: Patch isilon-creds secret with updated credentials
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: isilon-creds
        namespace: "{{ powerscale_ns }}"
      data:
        config: "{{ encoded_config }}"
      type: Opaque

# Remove the secret file
- name: Remove secret file
  ansible.builtin.file:
    path: "{{ csi_powerscale_secret_path }}"
    state: absent
  failed_when: false
