# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Prepare kube node configs
  when: hostvars['127.0.0.1']['k8s_support']
  block:
    - name: Generate kube node configs
      ansible.builtin.include_tasks: kube_node_config.yml

    - name: Generate kube node configs
      ansible.builtin.include_tasks: update_kube_proxy.yml

    - name: Generate kube node configs
      ansible.builtin.include_tasks: generate_static_cloud_init_vars.yml

    - name: Generate kube node configs
      ansible.builtin.include_tasks: generate_dynamic_cloud_init_vars.yml
      tags: kubeadm_token

    - name: Get taints of control-plane nodes
      ansible.builtin.command:
        cmd: kubectl get node {{ item }} -o jsonpath='{.spec.taints}'
      loop: "{{ groups['kube_control_plane'] }}"
      register: node_taints
      changed_when: false

    - name: Add control-plane taint if not present
      ansible.builtin.command:
        cmd: kubectl taint nodes {{ item.item }} node-role.kubernetes.io/control-plane=:NoSchedule --overwrite
      loop: "{{ node_taints.results }}"
      when: "'node-role.kubernetes.io/control-plane' not in item.stdout"
      changed_when: true

    # - name: Remove control-plane taint from kube_control_plane nodes
    #   ansible.builtin.command:
    #     cmd: kubectl taint nodes {{ item }} node-role.kubernetes.io/control-plane:NoSchedule
    #   loop: "{{ groups['kube_control_plane'] }}"
    #   run_once: true
