#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Render values.yaml.j2 template
  ansible.builtin.template:
    src: "{{ role_path }}/templates/kafka_values.yaml.j2"
    dest: "{{ kafka_values_yaml_path }}"
    mode: "{{ metadata_perm }}"

- name: Install kafka helm chart
  community.kubernetes.helm:
    release_name: kafka
    chart_ref: "{{ kafka_image_repo }}"
    chart_version: "{{ kafka_chart_version }}"
    namespace: "{{ telemetry_namespace }}"
    values_files:
      - "{{ kafka_values_yaml_path }}"
    wait: true
