- name: Deployment definition for Kafka broker StatefulSet
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: kafka
        namespace: "{{ telemetry_namespace }}"
      spec:
        serviceName: kafka-headless
        replicas: 1
        selector:
          matchLabels:
            app: kafka
        template:
          metadata:
            labels:
              app: kafka
          spec:
            nodeSelector:
              node-role.kubernetes.io/control-plane: ""
            tolerations:
              - key: "node-role.kubernetes.io/control-plane"
                operator: "Exists"
                effect: "NoSchedule"
            containers:
              - name: kafka
                image: bitnami/kafka:3.9.0
                env:
                  - name: KAFKA_PROCESS_ROLES
                    value: "broker,controller"
                  - name: KAFKA_NODE_ID
                    value: "0"
                  - name: KAFKA_CONTROLLER_QUORUM_VOTERS
                    value: "0@localhost:9093"
                  - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
                    value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
                  - name: KAFKA_LISTENERS
                    value: "PLAINTEXT://:9092,CONTROLLER://:9093"
                  - name: KAFKA_INTER_BROKER_LISTENER_NAME
                    value: "PLAINTEXT"
                  - name: KAFKA_ADVERTISED_LISTENERS
                    value: "PLAINTEXT://kafka-0.kafka-headless.telemetry.svc.cluster.local:9092"
                  - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
                    value: "1"
                  - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
                    value: "1"
                  - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
                    value: "1"
                  - name: ALLOW_PLAINTEXT_LISTENER
                    value: "yes"
                  - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
                    value: CONTROLLER
                  - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
                    value: "true"
                ports:
                  - containerPort: 9092
                  - containerPort: 9093
                volumeMounts:
                  - name: kafka-data
                    mountPath: /bitnami/kafka
        volumeClaimTemplates:
          - metadata:
              name: kafka-data
            spec:
              storageClassName: nfs-client
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi

- name: Kafka headless service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: kafka-headless
        namespace: "{{ telemetry_namespace }}"
        labels:
          app: kafka
      spec:
        clusterIP: None
        selector:
          app: kafka
        ports:
          - name: broker
            port: 9092

- name: Kafka LoadBalancer service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: kafka-loadbalancer
        namespace: "{{ telemetry_namespace }}"
        labels:
          app: kafka
      spec:
        type: LoadBalancer
        selector:
          app: kafka
        ports:
          - port: 9092
            targetPort: 9092
