# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Check version variable
  ansible.builtin.assert:
    that:
      - "item.version is defined"
      - item.version | default("",true) | length > 0
    fail_msg: "{{ version_invalid_fail_msg }} {{ item.name }}"

- name: Check if software repo file exists on node
  ansible.builtin.stat:
    path: "{{ repo_path }}/{{ item.name }}_{{ item.version }}.repo"
  register: repo_file_check

- name: Set fact for jinja template
  ansible.builtin.set_fact:
    software_item: "{{ item.name }}_{{ item.version }}"

- name: Check if base_url is present for the given software_item
  ansible.builtin.set_fact:
    baseurl_present: >-
      {{ (pulp_dist_result
           | selectattr('name', 'equalto', software_item)
           | map(attribute='base_url')
           | list
           | length > 0) | bool }}

- name: Create repo file on node
  ansible.builtin.template:
    src: "{{ repo_config_template_src }}"
    dest: "{{ repo_path }}/{{ software_item }}.repo"
    mode: "{{ file_permission }}"
  when: baseurl_present

- name: Set repos_update_status
  ansible.builtin.set_fact:
    repos_update_status: true
