# Copyright 2025 Intel Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Get K8s pods
  ansible.builtin.command: kubectl get pods --all-namespaces
  changed_when: false
  register: k8s_pods

- name: Deploy Gaudi metric exporter daemonset
  ansible.builtin.command: "kubectl apply -f {{ gaudi_metric_exporter_daemonset_url }}"
  changed_when: true
  when: "'metric-exporter-ds' not in k8s_pods.stdout"

- name: Get K8s services
  ansible.builtin.command: kubectl get service --all-namespaces
  changed_when: false
  register: k8s_services

- name: Deploy Gaudi metric exporter service
  ansible.builtin.command: "kubectl apply -f {{ gaudi_metric_exporter_service_url }}"
  changed_when: true
  when: "'metric-exporter' not in k8s_services.stdout"

- name: Get K8s servicemonitors
  ansible.builtin.command: kubectl get servicemonitor --all-namespaces
  changed_when: false
  register: k8s_serviemonitors

- name: Deploy Gaudi metric exporter service monitor
  ansible.builtin.command: "kubectl apply -f {{ gaudi_metric_exporter_servicemonitor_url }}"
  changed_when: true
  when: "'metric-exporter' not in k8s_serviemonitors.stdout"

- name: Add label to the ServiceMonitor so it will be scraped by Prometheus
  ansible.builtin.command: >
    kubectl patch servicemonitor metric-exporter
    -n monitoring
    --type='merge'
    -p '{"metadata": {"labels": {"release": "prometheus"}}}'
  changed_when: true
  when: "'metric-exporter' not in k8s_serviemonitors.stdout"
