# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Saving distribution and version of OS
  ansible.builtin.set_fact:
    oim_os: "{{ ansible_distribution | lower }}"
    oim_os_version: "{{ ansible_distribution_version | lower }}"

- name: Include local_repo variables
  ansible.builtin.include_tasks: include_local_repo_config.yml

- name: Check xcat installation status
  ansible.builtin.include_tasks: validate_amd.yml

- name: Check xcat installation status
  ansible.builtin.include_tasks: validate_intel_gaudi.yml

- name: Check if both intelgaudi and amdgpu not present in software_config.json
  ansible.builtin.fail:
    msg: "{{ driver_not_found_msg }}"
  when: >
    hostvars['localhost']['intel_gaudi_config_status'] is defined and
    hostvars['localhost']['amdgpu_config_status'] is defined and
    not hostvars['localhost']['intel_gaudi_config_status'] | bool and
    not hostvars['localhost']['amdgpu_config_status'] | bool
